services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    # ホストモード時はports指定不要ですが、管理用に残しておきます
    ports:
      - "8086:8086"
    env_file:
      - .env  # これでコンテナOSの環境変数に登録される
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  hems-app:
    build: .
    container_name: hems_app
    # 重要：これでパワコン(192.168.0.142)と直接通信可能になります
    # Linuxの場合は、コメントを外す
    #network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8000:8000"  # 左側がブラウザで打つポート、右側がFlaskのポート
      - "3610:3610/udp" # ECHONET用 (UDPを明示)
    depends_on:
      - influxdb
    env_file:
      - .env  # これでコンテナOSの環境変数に登録され
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /app

volumes:
  influxdb_data:
